### ISSUE TITLE
Unable to enter the background normally, the luci interface reports an error

### ISSUE THREAD

**Issue by small-white-rabbit** [boretom/OpenWrt#1]
I don't know if it's because of the theme I added or the source code, can you share a firmware that can be used normally? Or share the configuration file

**Comment by boretom** [comment]
I'm not sure you really wanted to report this here, that's just a fork of the official OpenWrt repo.

**Comment by small-white-rabbit** [comment]
Yes I know, because I just used my wax206, but it is not officially supported yet

**Comment by boretom** [comment]
Ok, I see. The configuration file (diff) I use I can share, sure.

<details><summary>OpenWrt config diff</summary>

````
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_mt7622=y
CONFIG_TARGET_mediatek_mt7622_DEVICE_netgear_wax206=y
CONFIG_LUA_ECO_DEFAULT_OPENSSL=y
CONFIG_LUA_ECO_OPENSSL=y
# CONFIG_LUA_ECO_WOLFSSL is not set
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_PACKAGE_attendedsysupgrade-common=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_ethtool=y
CONFIG_PACKAGE_kmod-fixed-phy=y
CONFIG_PACKAGE_kmod-libphy=y
CONFIG_PACKAGE_kmod-mdio-gpio=y
CONFIG_PACKAGE_kmod-mdio-netlink=y
CONFIG_PACKAGE_kmod-mhi-bus=y
CONFIG_PACKAGE_kmod-mhi-pci-generic=y
CONFIG_PACKAGE_kmod-mii=y
CONFIG_PACKAGE_kmod-of-mdio=y
CONFIG_PACKAGE_kmod-phy-realtek=y
# CONFIG_PACKAGE_kmod-ppp is not set
CONFIG_PACKAGE_kmod-sched-cake=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_libbz2=y
CONFIG_PACKAGE_libevent2-core=y
CONFIG_PACKAGE_libfdt=y
CONFIG_PACKAGE_libiwinfo-lua=m
CONFIG_PACKAGE_liblua=m
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblzma=y
CONFIG_PACKAGE_libmagic=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_librt=y
CONFIG_PACKAGE_libsmartcols=y
CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_libtirpc=y
CONFIG_PACKAGE_libubus-lua=m
CONFIG_PACKAGE_lscpu=y
CONFIG_PACKAGE_lsof=y
CONFIG_PACKAGE_lua=m
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-attendedsysupgrade=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-ssl=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_mdio-tools=y
CONFIG_PACKAGE_mii-tool=y
CONFIG_PACKAGE_mt76-test=y
CONFIG_PACKAGE_nand-utils=y
# CONFIG_PACKAGE_ppp is not set
CONFIG_PACKAGE_px5g-wolfssl=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rpcsys=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_tcpdump=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_tmux=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_vim-full=y
CONFIG_PACKAGE_zlib=y
CONFIG_PACKAGE_kmod-lib-crc-ccitt=y
```

</details>

What is the error you are getting and with which branch are you working?

**Comment by small-white-rabbit** [comment]
thank you buddy ：）

**Comment by boretom** [comment]
I assume you know how to use the diff? copy to OpenWrt folder as `.config` and run `make defconfig`.

**Comment by small-white-rabbit** [comment]
yes i know thanks a lot!

**Comment by boretom** [comment]
@small-white-rabbit, can I close this issue?

I'm cleaning up this repo since I created a PR for OpenWrt on another OpenWrt (https://github.com/boretom/openwrt-fork, because I messed up this repo when forking and it got connection to the OpenWrt repo)

**Comment by small-white-rabbit** [comment]
Yes, you can turn it off. Recently, I found that the compiled openwrt will always be disconnected. I don’t know why. I don’t know if you can share your compiled version and I will test it.

**Comment by boretom** [comment]
You find the compile output for my latest compile from yesterday in [this shared MEGA folder](https://mega.nz/folder/sUwjnTTJ#1Do_HbcTZ-MPXVoqLbHaag)

What do you mean by "always disconnected"? The WAN interface or the (one of the) LAN interfaces are disconnected?

Right now the WAN interface works up to 1G and if you connect the WAN to a switch which can handle faster speed, the WAN interface will auto-neg to 2.5G but it will not work (yet) in 2.5G mode. You would have to manually set the speed to 1G on either the switch or in OpenWrt using `ethtool` (`ethtool -s wan speed 1000 duplex full`)

**Comment by small-white-rabbit** [comment]
The main reason is that the wifi is disconnected. The test found that sometimes it occurs once every few hours, and sometimes it occurs once every few tens of minutes. The ping test shows that the delay increases, timeouts, and finally the wifi drops and reconnects. Thank you so much for sharing

**Comment by boretom** [comment]
I see, if you got a OpenWrt forum account, maybe this question is better answered [OpenWrt support for WAX206](https://forum.openwrt.org/t/openwrt-support-for-wax206/127523). There are a few people who do run it as an AP for some time.

**Comment by small-white-rabbit** [comment]
Ok, thank you very much for your reply, I will try it
